{
  "openapi": "3.0.0",
  "info": {
    "title": "temp",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID."
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the information of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        }
      }
    },
    "/user/profile": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "201": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "keycloakId": "c0c52fd1-e9de-456c-b553-8d408e8d2a42",
                      "name": {
                        "firstName": "Foo",
                        "lastName": "Bar"
                      },
                      "roles": [
                        "CONSUMER"
                      ],
                      "userId": "67194fc9-495e-40f7-b016-4470c1d4397f",
                      "clients": [
                        {
                          "client": "default",
                          "clientId": "6d0b58c3-c0c4-48af-bca2-4f255c0e73a7",
                          "clientSecret": "a18cb9fc-06b3-4ae5-8220-86fc4e89a1a6"
                        }
                      ],
                      "email": "ngoaf@chspomvjuq.com"
                    }
                  },
                  "properties": {
                    "keycloakId": {
                      "type": "string",
                      "minLength": 1
                    },
                    "name": {
                      "type": "object",
                      "required": [
                        "firstName",
                        "lastName"
                      ],
                      "properties": {
                        "firstName": {
                          "type": "string",
                          "minLength": 1
                        },
                        "lastName": {
                          "type": "string",
                          "minLength": 1
                        }
                      }
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "userId": {
                      "type": "string",
                      "minLength": 1
                    },
                    "clients": {
                      "type": "array",
                      "uniqueItems": true,
                      "minItems": 1,
                      "items": {
                        "type": "object",
                        "properties": {
                          "client": {
                            "type": "string",
                            "minLength": 1
                          },
                          "clientId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "clientSecret": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "client",
                          "clientId",
                          "clientSecret"
                        ]
                      }
                    },
                    "email": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "keycloakId",
                    "name",
                    "roles",
                    "userId",
                    "clients",
                    "email"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "keycloakId": "c0c52fd1-e9de-456c-b553-8d408e8d2a42",
                      "name": {
                        "firstName": "Foo",
                        "lastName": "Bar"
                      },
                      "roles": [
                        "CONSUMER"
                      ],
                      "userId": "67194fc9-495e-40f7-b016-4470c1d4397f",
                      "clients": [
                        {
                          "client": "default",
                          "clientId": "6d0b58c3-c0c4-48af-bca2-4f255c0e73a7",
                          "clientSecret": "a18cb9fc-06b3-4ae5-8220-86fc4e89a1a6"
                        }
                      ],
                      "email": "ngoaf@chspomvjuq.com"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "roles": {
                    "type": "array",
                    "uniqueItems": true,
                    "minItems": 1,
                    "maxItems": 3,
                    "items": {
                      "type": "string",
                      "enum": [
                        "consumer",
                        "provider",
                        "delegate"
                      ]
                    }
                  },
                  "orgId": {
                    "type": "string",
                    "description": "The organization ID",
                    "format": "uuid"
                  },
                  "phone": {
                    "type": "string",
                    "minLength": 10,
                    "maxLength": 10
                  }
                },
                "required": [
                  "roles"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user."
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "description": "",
        "x-examples": {
          "Alice Smith": {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        },
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for the given user."
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "example": "1997-10-31"
          },
          "emailVerified": {
            "type": "boolean",
            "description": "Set to true if the user's email has been verified."
          },
          "createDate": {
            "type": "string",
            "format": "date",
            "description": "The date that the user was created."
          }
        },
        "required": [
          "id",
          "firstName",
          "lastName",
          "email",
          "emailVerified"
        ]
      }
    }
  }
}